# Generated by Django 5.2.17 on 2026-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-fixado', '-criado_em']},
        ),
        migrations.AddField(
            model_name='aviso',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
    ]
