# Generated by Django 5.2.17 on 2026-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termo aceito em'),
        ),
        migrations.AddField(
            model_name='user',
            name='termos_versao_aceita',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='versão do termo aceita'),
        ),
    ]
